### ISSUE TITLE
Problemas al tratar de reemplazar texto

### ISSUE THREAD

**Issue by cleyan** [JorgeEMX/PDF_EDIT#1]
Hola
felicitaciones por el script, lo estoy tratando de implementar en un proyecto, pero tengo un problema
Al tratar de usar el script me sale un error: 

```
Fatal error: Uncaught exception 'Exception' with message 'TCPDF_PARSER ERROR: Invalid object reference: Array' in /var/www/vhosts/midom/pdf-test/tcpdf/tcpdf_parser.php:802
Stack trace:
#0 /var/www/vhosts/midom/pdf-test/tcpdf/tcpdf_parser.php(676): TCPDF_PARSER->Error('Invalid object ...')
#1 /var/www/vhosts/midom/pdf-test/tcpdf/tcpdf_parser.php(285): TCPDF_PARSER->getIndirectObject('0000680519', 1411636, true)
#2 /var/www/vhosts/midom/pdf-test/tcpdf/tcpdf_parser.php(194): TCPDF_PARSER->decodeXrefStream(1411636, Array)
#3 /var/www/vhosts/midom/pdf-test/tcpdf/tcpdf_parser.php(266): TCPDF_PARSER->getXrefData(1411636, Array)
#4 /var/www/vhosts/midom/pdf-test/tcpdf/tcpdf_parser.php(191): TCPDF_PARSER->decodeXref('1408644', Array)
#5 /var/www/vhosts/midom/pdf-test/pdf_edit.php(72): TCPDF_PARSER->getXrefData()
#6 /var/www/vhosts/midom/pdf-test/pdf_edit.php(108): PDF_EDIT->ReloadTcpdfData()
#7 /var/www/vhosts/midom/pdf-test/pdf_edit.php(397): PDF_EDIT->BuildPDFString()
#8 /var in /var/www/vhosts/midom/pdf-test/tcpdf/tcpdf_parser.php on line 802

```

El PDF lo pueden encontrar en:

https://drive.google.com/file/d/0B1vLm-nHXivDLW9RekVwdEVJeXc/view?usp=sharing

Fue generado con Adobe Illustartor, alguna considereción a tomar en cuenta? tamaños, características, etc

De antemano muchas gracias

Carlos

**Comment by JorgeEMX** [comment]
Gracias por el reporte, lo reviso para ver si se trata de algún bug. Por cierto, que parte del texto quieres editar? 

Saludos
